# Generated by Django 4.2.6 on 2023-10-17 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Visualizar view',
                'db_table': 'NewView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnLogFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Última info da frota',
                'db_table': 'onLogFleet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Frotas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Operações',
            },
        ),
        migrations.CreateModel(
            name='StatusFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Status da Frota',
            },
        ),
        migrations.CreateModel(
            name='StopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Grupos de parada',
            },
        ),
        migrations.CreateModel(
            name='StopReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.stopgroup')),
            ],
            options={
                'verbose_name_plural': 'Motivos de parada',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.location')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.operation')),
            ],
            options={
                'verbose_name_plural': 'Frentes',
            },
        ),
        migrations.CreateModel(
            name='LogAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.category')),
                ('fleetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.fleet')),
                ('operationFront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.operationfront')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.statusfleet')),
                ('stopReason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stopSystem.stopreason')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
