# Generated by Django 4.2.6 on 2023-10-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopSystem', '0002_delete_onlogfleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusfleet',
            name='typeLog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stopSystem.typelog', verbose_name='type_log'),
        ),
    ]
