# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations
import stopSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('stopSystem', '0003_statusfleet_typelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='description',
            field=stopSystem.models.UppercaseTextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='logagricola',
            name='description',
            field=stopSystem.models.UppercaseTextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
