# Generated by Django 4.2.6 on 2023-11-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stopSystem', '0004_alter_fleet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typelog',
            name='isRequiredStopReason',
            field=models.BooleanField(db_column='is_requiered_stop_reason', default=True, verbose_name='Requerido Motivo de Parada'),
        ),
        migrations.AlterField(
            model_name='statusfleet',
            name='typeLog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stopSystem.typelog', verbose_name='Tipo de Log'),
        ),
    ]
