# Generated by Django 4.2.6 on 2023-11-06 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stopSystem', '0007_alter_logagricola_stopreasonid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typelog',
            name='isRequiredStopReason',
        ),
        migrations.AddField(
            model_name='statusfleet',
            name='isRequiredStopReason',
            field=models.BooleanField(db_column='is_requiered_stop_reason', default=True, verbose_name='Informar Motivo de Parada'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='stopReasonId',
            field=models.ForeignKey(blank=True, db_column='stop_reason_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stopSystem.stopreason', verbose_name='Motivo Parada/Notificação'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='updatedAt',
            field=models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now, verbose_name='Última Atualização'),
        ),
    ]
